notebook/content/urls.py
from django.conf.urls import include, url


from .views import (
        add_record,
        list_record,
        update_record,
        delete_record,
    )

urlpatterns = [
    url(r'^add_record/', add_record, name="add_record"),
    url(r'^update_record/(?P<id>\d+)/$', update_record, name="update_record"),
    url(r'^delete_record/(?P<id>\d+)/$', delete_record, name="delete_record"),
    url(r'^', list_record, name="list_record"),
]

notebook/loginsys/urls.py
from django.conf.urls import include, url


from .views import (
        login,
        logout,
        register,
    )

urlpatterns = [
    url(r'^login/$', login, name="login"),
    url(r'^logout/$', logout, name="logout"),
    url(r'^register/$', register, name="register"),
]

notebook/notebook/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('loginsys.urls', namespace="loginsys")),
    url(r'^', include('content.urls', namespace="content")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notebook/content/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.core.validators import RegexValidator

# Create your models here.
class RecordNotebook(models.Model):
    class Meta():
        db_table = 'record_notebook'

    owner           = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    full_name       = models.CharField(max_length=64)
    phone_regex     = RegexValidator(regex=r'^\+?1?\d{6,15}$', message="format: '+999999'. Up to 15 digits allowed.")
    phone_number    = models.CharField(validators=[phone_regex], blank=False, max_length=15) # validators should be a list
    birthday        = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return "Record: %s" % self.full_name

notebook/loginsys/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

notebook/content/forms.py
from django import forms

from .models import RecordNotebook


class RecordForm(forms.ModelForm):

    class Meta:
        model = RecordNotebook
        fields = [
            "full_name",
            "phone_number",
            "birthday",
        ]

notebook/content/views.py
from django.shortcuts import render, render_to_response, redirect, get_object_or_404
from django.http.response import HttpResponse
from django.http import HttpResponse, HttpResponseRedirect, Http404

from .forms import RecordForm
from .models import RecordNotebook
from datetime import datetime

from django.db.models import Q

# Create your views here.

#*******************************************************************************
def add_record(request):
    if not request.user.is_authenticated():
        return redirect("loginsys:login")

    form = RecordForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            instance        = form.save(commit=False)
            date_birthday   = instance.birthday
            if date_birthday is not None: #Check: The user was not born yet
                birthday    = datetime(date_birthday.year, date_birthday.month, date_birthday.day)
                if birthday > datetime.today():
                    context = {
                        "error"     : "Error: The user was not born yet",
                        "title"     : "Create",
                        "input1"    : "New contact",
                        "input2"    : "Create a new contact",
                        "form"      : form,
                    }
                    return render(request, "record_form.html", context)
            
            instance.owner  = request.user
            instance.save()
            return redirect("content:list_record")

    context = {
        "title"     : "Create",
        "input1"    : "New contact",
        "input2"    : "Create a new contact",
        "form"      : form,
    }
    return render(request, "record_form.html", context)

#*******************************************************************************

def list_record(request):
    if not request.user.is_authenticated():
        return redirect("loginsys:login")

    queryset_list = queryset_list = RecordNotebook.objects.filter(owner=request.user)
    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
                                            Q(full_name__icontains=query)|
                                            Q(phone_number__icontains=query)|
                                            Q(birthday__icontains=query)
                                            ).distinct()
    
    today = datetime.now().date()
    queryset_birthday = RecordNotebook.objects.filter(owner=request.user, birthday__day=today.day, birthday__month=today.month)
    context = {
        "title"             : "Contacts",
        "object_list"       : queryset_list,
        "queryset_birthday" : queryset_birthday,
    }
    return render(request, "list_record.html", context)

#*******************************************************************************

def update_record(request, id=None):
    if not request.user.is_authenticated():
        return redirect("loginsys:login")#redirect to login

    instance    = get_object_or_404(RecordNotebook, id=id)
    form        = RecordForm(request.POST or None, instance=instance)

    if instance.owner == request.user:
        if form.is_valid():
            instance        = form.save(commit=False)
            date_birthday   = instance.birthday
            if date_birthday is not None:
                birthday    = datetime(date_birthday.year, date_birthday.month, date_birthday.day)
                if birthday > datetime.today():
                    context = {
                        "error"     : "Error: The user was not born yet",
                        "title"     : "Edit",
                        "input1"    : "Edit",
                        "input2"    : "Update contact",
                        "form"      : form,
                    }
                    return render(request, "record_form.html", context)

            instance.save()    
            return redirect("content:list_record")
        context = {
            "title"     : "Update",
            "input1"    : "Update the contact",
            "input2"    : "Edit contact",
            "form"      : form,
        }
        return render(request, "record_form.html", context)
    else:
        return Http404

#*******************************************************************************

def delete_record(request, id=None):
    if not request.user.is_authenticated():
        return redirect("loginsys:login")#redirect to login

    instance    = get_object_or_404(RecordNotebook, id=id)
    if instance.owner == request.user:
        instance.delete()
        return redirect("content:list_record")
    else:
        return Http404

#*******************************************************************************

notebook/loginsys/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm

def login(request):
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user:
            auth.login(request, user)
            return redirect('content:list_record')
        else:
            return render(request, 'login.html', {
              	'login_error': "* User not found",
              })
    else:
        return render(request, 'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password2']
            user = auth.authenticate(username=username, password=password)
            auth.login(request, user)
            return redirect('loginsys:login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

notebook/templates/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>
<head>
<title>{% block head_title %} Notebook {% endblock head_title %}</title>

{% block init_static %}
    <meta charset="utf-8">
    <meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <!--************************************************************-->
    <title>{% block title %} Adblock sucks! {% endblock title%}</title>
    <!--************************************************************-->
    <link rel="shortcut icon" href="{%   static 'images/gt_favicon.png' %}">
    
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    <!-- Custom styles for our template -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}" media="screen" >
    <link rel="stylesheet" href="{% static 'css/main.css' %} ">
    
    <!--************************************************************-->
    {% block javascript %}
    <!-- JavaScript libs are placed at the end of the document so the pages load faster -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="/static/js/headroom.min.js"></script>
    <script src="/static/js/jQuery.headroom.min.js"></script>
    <script src="/static/js/template.js"></script>
    
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.min.css" />
    <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    
    {% endblock javascript%}
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="static/js/html5shiv.js"></script>
    <script src="static/js/respond.min.js"></script>
    <![endif]-->
    {% endblock init_static %}

</head>

<!-- <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">


<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

</head>-->


<body>

{% block navbar%}
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top headroom" >
        <div class="container">
            <div class="navbar-header">
                <!-- Button for smallest screens -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                <a class="navbar-brand" href="{% url 'content:list_record' %}"><img src="/static/images/logo1.png" alt="Progressus HTML5 template"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right">
                    
                    <!-- Authenticate menu-->
                    {% if request.user.is_authenticated %}
                        
                        <li id="menu_add_site_li_id"><a href="{% url 'content:add_record' %}">Add contact</a></li>
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome ( {{request.user.username}} )<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="active"><a href="{% url 'loginsys:logout' %}">Logout</a></li>
                        </ul>
                        </li>

                    {% else %}
                        <li class="active"><a class="btn" href="{% url 'loginsys:login' %}">Sign In</a></li>
                        <li class="active"><a class="btn" href="{% url 'loginsys:register' %}">Sign Up</a></li>
                    {% endif %}
                    <!-- Authenticate menu-->
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
    
    <header id="head" class="secondary"></header> 
    
    <!-- /.navbar -->
    {% endblock navbar%}


    {% block content %}{% endblock content %}





    {% block footer%}
        <footer id="footer" class="top-space">

        <div class="footer1">
            <div class="container">
                <div class="row">
                    
                    <div class="col-md-3 widget">
                        <h3 class="widget-title">Contact</h3>
                        <div class="widget-body">
                            <p>8 999 209 72 53<br>
                                <a href="mailto:#">falko.ftk@gmail.com</a><br>
                                <br>
                                16 Kharchenko street, St. Petersburg
                            </p>    
                        </div>
                    </div>

                    <div class="col-md-6 widget">
                        <h3 class="widget-title">About me</h3>
                        <div class="widget-body">
                            <p>I would like to start a career in a team of qualified experienced employees. It takes over all experience and knowledge to achieve the rank of Senior developer and in perspective Team leader</p>
                            <p>I like to speak in public, especially at scientific conferences. I love sports such as running, cross fit, football. I try not to miss interesting articles on Habrahabr and Formula 1 races</p>
                        </div>
                    </div>

                </div> <!-- /row of widgets -->
            </div>
        </div>

        <div class="footer2">
            <div class="container">
                <div class="row">
                    
                    <div class="col-md-6 widget">
                        <div class="widget-body">
                            <p class="simplenav">
                                <a href="{% url 'content:list_record' %}">Home</a> | 
                                {% if request.user.is_authenticated %}
                                | <a href="{% url 'content:add_record' %}">Add site</a>
                                | <a href="{% url 'content:list_record' %}">My sites</a>
                                {% else %}
                                | <b><a href="{% url 'loginsys:login' %}">Sign in</a></b>
                                | <b><a href="{% url 'loginsys:register' %}">Sign up</a></b>
                                {% endif %}
                            </p>
                        </div>
                    </div>

                    <div class="col-md-6 widget">
                        <div class="widget-body">
                            <p class="text-right">
                                Copyright &copy; 2016, notebook.falko 
                            </p>
                        </div>
                    </div>

                </div> <!-- /row of widgets -->
            </div>
        </div>
        </footer>
    {% endblock footer%}



</body>
</html>

notebook/templates/list_record.html
{% extends "base.html" %}
{% block content %}

<div class="container">

		<div class="row">
			
			<!-- Sidebar -->
			<aside class="col-md-4 sidebar sidebar-left">

				<div class="row widget">
					<div class="col-xs-12">
						<h4><b>Birthday reminder</b></h4>
						{% if queryset_birthday %}
							{% for today in queryset_birthday %}
							<p><b>{{today.full_name}} : {{today.phone_number}} <img src="/static/images/birthday.png" alt="" </b></p>
							<hr/>
						{% endfor %}
						{% else %}
							<p>Today there aren't birthday in your contacts</p>
						{% endif %}
					</div>
				</div>
				<div class="row widget">
					<div class="col-xs-12">
						<h4>Contact center</h4>
						<p><img src="/static/images/contact.png" alt=""></p>
					</div>
				</div>
				<div class="row widget">
					<div class="col-xs-12">
						
					</div>
				</div>

			</aside>
			<!-- /Sidebar -->

			<!-- Article main content -->
			<article class="col-md-8 maincontent">
				<!--<header class="page-header">
					<h1 class="page-title">Contacts</h1>
				</header>-->
					<div class="container">
						  <h2>Contacts / <a href="{% url 'content:add_record' %}">New contact</a></h2>
						  <p><form method='GET' action=''> <input type='text' name='q' placeholder='Search' value='{{ request.GET.q }}'/>
                        	<input type='submit' value='Go' />
                        	</form></p>            
						  <table class="table table-striped">
						    <thead>
						      <tr>
						        <th>Fullname</th>
						        <th>Phone</th>
						        <th>Birthday</th>
						      </tr>
						    </thead>
						    <tbody>
						    {% for obj in object_list %}
						      <tr>
						        <td><a href='{% url "content:update_record" id=obj.id %}'>{{obj.full_name}}</a></td>
						        <td>{{obj.phone_number}}</td>

						        {% if obj.birthday %}
						        <td>{{obj.birthday}}</td>
						        {% else %}
						        <td>---</td>
						        {% endif %}
						        <td><a href='{% url "content:delete_record" id=obj.id %}'><b>delete</b></a></td>
						      </tr>
						    {% endfor %}
						    </tbody>
						  </table>
					</div>
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->



{% endblock content %}

notebook/templates/login.html
{% extends 'base.html' %}

{% block content %}



<!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->

            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Sign in</h1>
                </header>

                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="thin text-center">Sign in</h3>
                            <p class="text-center text-muted">To sign in, enter your username and password</p>
                            <hr>

                            <form method="post" action="{% url 'loginsys:login' %}">
                                {% csrf_token %}

                                {% if form.non_field_errors %}
                                <ul class='form-errors'>
                                {% for error in form.non_field_errors %}
                                <li>{{ error }}</li>
                                {% endfor %}
                                </ul>
                                {% endif %}

                                {% if login_error %}
                                    <p>{{ login_error }}</p>
                                {% endif %}


                                <div class="top-margin">
                                    <p><label for="id_username">Username </label> <input id="id_username" name="username" type="text" class="form-control" /></p>
                                </div>
                                <div class="top-margin">
                                    <p><label for="id_password">Password </label> <input id="id_password" name="password" type="password" class="form-control"/></p>
                                </div>

                                <hr/>
                                <div class="row">
                                    <div class="col-lg-8">
                                        <!--<button class="btn btn-action" type="submit">Log in</button>-->
                                        <input class="btn btn-action" type="submit" value="Sign in" />
                                    </div>
                                    <div class="col-lg-8">
                                    <hr/>
                                    <p class="text-muted">Don't have an account?<a href="{% url 'loginsys:register' %}" class="button">Sign up</a></p>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </article>


            <!-- /Article -->

        </div>
    </div>  <!-- /container -->

{% endblock content %}

notebook/templates/record_form.html
{% extends "base.html" %}

{% block head_title %} {{ title }}{% endblock head_title %}

{% block content %}
<!-- container -->
    <div class="container">

        <div class="row">
            
            <!-- Article main content -->

            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">{{input1}}</h1>
                </header>
                
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="thin text-center">{{input2}}</h3>
                            <hr>

                            <form method="post" action="">
                                {% csrf_token %}

                                <div class="top-margin">
                                    {{ form.full_name.errors }}
                                    {%if form.full_name.value %}
                                    <p class="required"><label class="required" for="full_name">Fullname </label> 
                                    <input id="full_name" placeholder="Fullname" maxlength="64" name="full_name" type="text" class="form-control" value="{{form.full_name.value}}"/></p>
                                    {%else%}
                                    <p class="required"><label class="required" for="full_name">Fullname </label> 
                                    <input id="full_name" placeholder="Fullname" maxlength="64" name="full_name" type="text" class="form-control"/></p>
                                    {%endif%}

                                </div>

                                <div class="row top-margin">
                                    <div class="col-sm-6">
                                        {{ form.phone_number.errors }}
                                        {%if form.phone_number.value %}
                                        <p class="required"><label class="required" for="phone_number">Phone </label> 
                                        <input id="phone_number" placeholder="+89993331177" maxlength="15" name="phone_number" type="text" class="form-control" value="{{form.phone_number.value}}"/></p>
                                        {%else%}
                                        <p class="required"><label class="required" for="phone_number">Phone </label> 
                                        <input id="phone_number" placeholder="89993331177" maxlength="15" name="phone_number" type="text" class="form-control"/></p>
                                        {%endif%}

                                    </div>
                                    <div class="col-sm-6">
                                        {{ form.birthday.errors }}
                                        {% if error %}
                                        <p>{{ error }}</p>
                                        {% endif %}

                                        {%if form.birthday.value and error %}
                                        <p><label for="birthday">Birthday </label>
                                        <input id="birthday" placeholder="1980-01-01" name="birthday" type="text" class="form-control"/></p>

                                        {% elif form.birthday.errors %}
                                        <p><label for="birthday">Birthday </label>
                                        <input id="birthday" placeholder="1980-01-01" name="birthday" type="text" class="form-control"/></p>
                                        {%elif form.birthday.value %}
                                        <p><label for="birthday">Birthday </label> 
                                        <input id="birthday" placeholder="1980-01-01" name="birthday" type="text" class="form-control" value="{{form.birthday.value.year}}-{{form.birthday.value.month}}-{{form.birthday.value.day}}"/></p>
                                        {%else%}
                                        <p><label for="birthday">Birthday </label>
                                        <input id="birthday" placeholder="1980-01-01" name="birthday" type="text" class="form-control"/></p>
                                        {%endif%}

                                    </div>
                                </div>

                                <hr>

                                <div class="row">
                                    <div class="col-lg-4">
                                        
                                        <button class="btn btn-action" type="submit">Apply</button>
                                    </div>
                                    </div>
                            </form>
                        </div>
                    </div>

                </div>
                
            </article>
            
            
            <!-- /Article -->

        </div>
    </div>    <!-- /container -->

{% endblock content%}

notebook/templates/register.html
{% extends 'base.html' %}




{% block content %}
<!-- container -->
    <div class="container">

        <div class="row">
            
            <!-- Article main content -->

            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Registration</h1>
                </header>
                
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="thin text-center">Create an account</h3>
                            <hr>

                            <form method="post" action="{% url 'loginsys:register' %}">
                                {% csrf_token %}

                                <div class="top-margin">
                                    {{ form.username.errors }}
                                    <p class="required"><label class="required" for="id_username">Username </label> 
                                    <input id="id_username" maxlength="30" placeholder="Username" name="username" type="text" class="form-control"/> </p>

                                </div>

                                <div class="row top-margin">
                                    <div class="col-sm-6">
                                        {{ form.password1.errors }}
                                        <p class="required"><label class="required" for="id_password1">Password </label> 
                                        <input id="id_password1" name="password1" placeholder="Password" type="password" class="form-control"/></p>

                                    </div>
                                    <div class="col-sm-6">
                                        {{ form.password2.errors }}
                                        <p class="required"><label class="required" for="id_password2">Confirm Password </label> 
                                        <input id="id_password2" name="password2" placeholder="Confirm password" type="password" class="form-control"/> </p>

                                    </div>
                                </div>

                                <hr>

                                <div class="row">
                                    <div class="col-lg-4">
                                        
                                        <button class="btn btn-action" type="submit">Create</button>
                                    </div>
                                    </div>
                            </form>
                        </div>
                    </div>

                </div>
                
            </article>
            
            
            <!-- /Article -->

        </div>
    </div>    <!-- /container -->

{% endblock content%}